### PR TITLE
Added handler_map to SocketIO class

### PR DESCRIPTION
**Pull request by bpengu1n**
Added handler_map to SocketIO class permitting iteration over endpoints and their handler functions i.e. for autodoc purposes.

### CODE REVIEW

**Comment by bpengu1n** [comment]
Resolved concerns raised in #573

**Comment by bpengu1n** [comment]
@miguelgrinberg Kept this very simple, just a list to iterate message -> handler. Works great with the Sphinx plugin I'm developing to generate API docs for Flask_SocketIO endpoints. Happy to address any modifications you think should occur!

**Comment by miguelgrinberg** [comment]
@bpengu1n Thanks, this helps me better understand what your needs are. Is this Sphinx plugin that you are writing something internal for your project or is it a public available plugin? Can I take a quick look at it if the latter?

The change that you made is safe, but can't help but bother a bit about duplicating the list of handlers, so I'd like to explore if there is a better way.

**Comment by bpengu1n** [comment]
@miguelgrinberg That's understandable! I intend to make the plugin public, basing it currently on the 'autohttp' plugin, though I will likely end up refactoring it into an entirely new plugin as autohttp/httpdomain likely won't end up being a good fit for it.
See https://github.com/bpengu1n/httpdomain/blob/flask_socketio/sphinxcontrib/autohttp/flask_socketio.py

**Comment by miguelgrinberg** [comment]
@bpengu1n after some thought I decided to add the `@wraps` decorator as initially suggested in #573.

**Pull request closed without merging**
