### PR TITLE
Remove executable permissions from files that lack shebang lines

### PR DESCRIPTION
**Pull request by musicinmybrain**
A file that does not have a shebang (“#!/usr/bin/python3” or similar)
cannot be executed as a script, so its filesystem permissions should not
include the executable bit.

This corresponds to https://github.com/miguelgrinberg/python-socketio/pull/748 and https://github.com/miguelgrinberg/python-engineio/pull/240. Here, there are a couple of example files (`example/app.py` and `example/app_namespace.py` that have `#!/usr/bin/env python` shebangs, so their executable permissions are retained.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
I would rather make everything consistent and remove the shebangs from the files that have them.

**Comment by musicinmybrain** [comment]
> I would rather make everything consistent and remove the shebangs from the files that have them.

Are you sure? Those two files have an `if __name__ == '__main__':` and actually do something reasonable (run the Flask development server) when invoked as scripts. It’s probably the most obvious way to try out the example.

You know the code best, of course, and if you confirm that’s what you want, I’ll add a commit that removes the shebang files and executable permissions from those two files. Running them with `python3 -m example.app` will still work.

**Comment by miguelgrinberg** [comment]
> Are you sure?

Well, yes. If you don't think this is okay, then why are you removing the executable bits in all the scripts? Wouldn't it make more sense to add shebangs everywhere instead?

I don't really care which style is used, as long as it is consistent. I will never document running a Python script as `./app.py` because that is a Unix-specific thing that does not work on Windows, as far as documentation it will always be `python app.py`.

**Comment by musicinmybrain** [comment]
You confirmed your intent, so I added a commit to remove the remaining shebangs and executable permissions. Thank you for your feedback.

(If it matters, your position seems reasonable, and I have no reason to push an alternative approach.)

**Comment by miguelgrinberg** [comment]
Thanks!

**Pull request merged**
