### PR TITLE
@wraps decorator to expose underlying method documentation

### PR DESCRIPTION
**Pull request by hsvlz**
Hi Miguel,

adding a @wraps decorator to expose underlying method documentation for every socketio.on event

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
@hsvlz the decorator does not wrap the original function, it returns the original function. Did you see a situation in which the documentation of the original function was lost?

**Comment by hsvlz** [comment]
When iterating over socketio.server.handlers.items() in my function generating the documentation:

```
for namespace, rules in socketio.server.handlers.items():
       for rule, func in rules.items():
```

func ends up always being _handler with no access to func_name or func_docs. By adding this @wraps, I can access the underlying function information of a function using the decorator @socketio.on(...)

**Comment by miguelgrinberg** [comment]
Are you aware that `socketio.server` is undocumented in Flask-SocketIO, and that `server.handlers` is undocumented in python-socketio, right? Those can change without deprecation or even notice, because applications are not supposed to use them.

**Comment by hsvlz** [comment]
Is there an alternative public way to iterate over function handlers, the same way it is safe to iterate over current_app.url_map.iter_rules() in flask?

**Comment by miguelgrinberg** [comment]
No, there is currently no official way to iterate over the handlers. You could use a custom decorator to mark functions as needing documentation to avoid using the private attributes.

**Comment by hsvlz** [comment]
The issue with adding custom decorators for documentation is:
- decorator hell (functions could end up with quite a few decorators and you need to repeat it for every single method)
- unnecessary decorators are applied - for instance in production, documentation will be turned off, and therefore maintaining unnecessary data-structures and code for documentation will be executed regardless

@socketio.on() is guaranteed to be a decorator, therefore adding @wraps should not affect your implementation. I agree that your underlying implementation could evolve, and that both socketio.server and server.handlers are undocumented - I am using them at my own peril and should the implementation change, I would adapt.

**Comment by miguelgrinberg** [comment]
I'll think about this. It may make more sense to provide an iterator that can give you the actual functions, not the internal wrapper.

**Comment by hsvlz** [comment]
That would work for me! Thank you Miguel.

**Comment by bpengu1n** [comment]
@miguelgrinberg Has there been any progress on adding an iterator for handler functions? If not, would you be open to a pull request submission for it? I'm writing a sphinx plugin to generate documentation for Flask_SocketIO API endpoints, and it's proving to be impractical without a way to get at those original references.

**Comment by miguelgrinberg** [comment]
@bpengu1n I haven't done any work on this issue. Open to accept a contribution for it. Thanks!

**Pull request closed without merging**
