### PR TITLE
Implement broadcasting to all but sender (close #75)

### LINKED ISSUE #75: Broadcast message to all users except for sender
Hello,
You mentioned to a user [on your blog](http://blog.miguelgrinberg.com/post/easy-websockets-with-flask-and-gevent/page/5) that they should submit this issue on github, but I couldn't find it--so just wanted to submit it for them ;). 

The third snippet of [this SO post](http://stackoverflow.com/a/10099325/1144523) shows how it can be done using the original socket.io server:

```
// sending to all clients, include sender
io.sockets.emit('message', "this is a test");

// sending to all clients except sender
socket.broadcast.emit('message', "this is a test");
```

Would this be possible to implement here? I'm not sure if this falls in the domain of this flask extension or gevent-socketio, as my websocket skills are fairly poor--but I'm happy to try to implement it if you have a sense for where it should go.

### PR DESCRIPTION
**Pull request by machow**
emit method now takes send_to_self variable (default is True). If
send_to_self is False and broadcast is True, then excludes the original sender when emitting. This
will still broadcast to everyone if not sent from a specific socket.

Expanded broadcasting unit tests to ensure only others receive the broadcast.

### CODE REVIEW

**Comment by spectralsun** [comment]
:+1: 
Merge this soon?

**Comment by miguelgrinberg** [comment]
Note that `request.namespace` is only available in the context of a socket.io event. For server-originated broadcasts it is obviously not available, but maybe that's all right, I don't think it makes sense to use this feature in server started events anyway.

**Comment by spectralsun** [comment]
@miguelgrinberg is it possible to store a clients namespace in an object and use that to send a message directly to that client in the request for a different client? Right now I'm grabbing IDs for the sockets like this:
`id = request.url.split('/')[-1]`

**Comment by miguelgrinberg** [comment]
@spectralsun Yes, you can use the namespace object from a user from another user's context.

**Comment by miguelgrinberg** [comment]
This option is going to be supported in the upcoming release 1.0.

**Comment by miguelgrinberg** [comment]
This has been reimplemented in the 1.0 release as the `include_self` argument to `emit()` and `send()`.

**Pull request closed without merging**
