### PR TITLE
Added SSL enablement for eventlet

### LINKED ISSUE #193: Configuring SSL with eventlet
Hi, 

Is there documentation anywhere about configuring SSL when using eventlet?

I see there was a comment [here](https://github.com/miguelgrinberg/Flask-SocketIO/issues/188#issuecomment-168351875) about already forwarding additional arguments to the server.

There is a snippet for Flask receiving an `ssl_context`: http://flask.pocoo.org/snippets/111/

Trying to pass around an `ssl_context` gives me an `unexpected keyword argument 'ssl_context'`. The same goes for `keyfile` and `certfile`, but I'm assuming that was specific to `gevent`.

```python
if __name__ == '__main__':
    certfile = os.path.join(ROOT_DIR, 'private/certificate.pem')
    keyfile = os.path.join(ROOT_DIR, 'private/privatekey.pem')

    # Ignore the None value as the keyword error happens before I get anywhere close to setting up SSL
    socketio.run(
        app,
        host='0.0.0.0',
        port=5000,
        ssl_context=None
    )
```

I'm trying to understand based on the documentation, but I've never done this with Flask, let alone with SocketIO integration. From eventlet's documentation, it looks like you create a `GreenSSLSocket`? I'm assuming you then pass that to `eventlet.wsgi.server(sock, site, ...)` as the socket. If that's the case, it doesn't look like I can do that since the socket is hard-coded here: https://github.com/muatik/Flask-SocketIO/blob/9cd254c5fdc45a2aa8f03ec372eddb2f74e8a7bb/flask_socketio/__init__.py#L378

If that's not the case and there is some way to do this (without adding something like nginx in front), please let me know or point me in the right direction!

### PR DESCRIPTION
**Pull request by chipsenkbeil**
Resolves #193. Still testing this. I ran with python2 on my host machine mapping with localhost and it works. I've got a Docker container with python3 that gets mapped through the address 192.168.99.100 and it hangs, but I'm not sure if this is a Docker issue or some issue with the code below.

If you want to test this yourself, please go ahead!

The options listed are what the GreenSSLSocket class takes in its constructor. My assumption is that if any of these options are provided, you intend to use SSL with eventlet. If you don't provide certfile, keyfile, etc. it appears that eventlet will throw its own error.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Very nice, thanks for taking the time to implement this fix! I'll test it tonight.

**Comment by chipsenkbeil** [comment]
Had a chance to test it yet?

**Comment by miguelgrinberg** [comment]
Did you test on Python 3? Everything looks good on Python 2.7, but I'm getting a strange error on Python 3 that I haven't been able to figure out yet.

    Traceback (most recent call last):
      File "/Users/miguelgrinberg/.pyenv/versions/3.4.3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()
      File "/Users/miguelgrinberg/.pyenv/versions/3.4.3/lib/python3.4/threading.py", line 868, in run
        self._target(*self._args, **self._kwargs)
      File "/Users/miguelgrinberg/Documents/dev/flask/flask-socketio/flask_socketio/__init__.py", line 394, in run_server
        log_output=log_output, **kwargs)
      File "/Users/miguelgrinberg/Documents/dev/flask/flask-socketio/venv/lib/python3.4/site-packages/eventlet/wsgi.py", line 823, in server
        client_socket = sock.accept()
      File "/Users/miguelgrinberg/Documents/dev/flask/flask-socketio/venv/lib/python3.4/site-packages/eventlet/green/ssl.py", line 333, in accept
        suppress_ragged_eofs=self.suppress_ragged_eofs)
      File "/Users/miguelgrinberg/Documents/dev/flask/flask-socketio/venv/lib/python3.4/site-packages/eventlet/green/ssl.py", line 88, in __init__
        self.do_handshake()
      File "/Users/miguelgrinberg/Documents/dev/flask/flask-socketio/venv/lib/python3.4/site-packages/eventlet/green/ssl.py", line 241, in do_handshake
        super(GreenSSLSocket, self).do_handshake)
      File "/Users/miguelgrinberg/Documents/dev/flask/flask-socketio/venv/lib/python3.4/site-packages/eventlet/green/ssl.py", line 106, in _call_trampolining
        return func(*a, **kw)
      File "/Users/miguelgrinberg/.pyenv/versions/3.4.3/lib/python3.4/ssl.py", line 810, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:600)

**Comment by miguelgrinberg** [comment]
Actually, I'll go ahead and merge. This seems to be an eventlet bug.

**Pull request closed without merging**
