### PR TITLE
Wrap app into DebugApplication in SocketIO.run()

### LINKED ISSUE #81: Using "DON'T PANIC" werkzeug traceback interpreter
It is mildly annoying to see "Internal Server Error" instead of nice web page with a stack trace.
Question: is it possible to somehow use DON'T PANIC? I would be willing to contribute if it requires not too much work.

### PR DESCRIPTION
**Pull request by eleweek**
This fixes #81 , and makes socketio.run() more similar to app.run()

### CODE REVIEW

**Comment by eleweek** [comment]
Update the pull-request, I made a mistake(see second commit)

**Comment by eleweek** [comment]
Bump! I ran into this issue again. Could you please look at this pull-request(it should fix it).

**Comment by eleweek** [comment]
Hi! Could you please review this pull-request?

**Comment by miguelgrinberg** [comment]
Okay, I can merge this change. Can you squash the two commits into one so that I get a single entry in the commit history?

**Comment by miguelgrinberg** [comment]
I believe the upcoming version 1.0 does this the way you suggest in this PR. Could you give the beta release a try and confirm?

    pip install flask-socketio==1.0b1

Thanks!

**Pull request closed without merging**
